### ISSUE TITLE
Un mini detalle

### ISSUE THREAD

**Issue by hbaravalle** [JuanesPachon/BIT-Cook-Final-Project#1]
Juan! El proyecto está muy muy bien! Como detalle, podrías ponerle 100% de alto a tus articles de la home para que, en caso de que el texto supere el propio alto de este elemento, no se sobresalga. Te dejo una captura de este comportamiento en un tamaño de pantallas muy muy grande (2000px):

![image](https://github.com/JuanesPachon/BIT-Cook-Final-Project/assets/24690415/1cdfec26-908e-4f95-813b-8b23ecdd8999)

Por supuesto lo esencial está cubierto. Este es un mini detalle para que tu sitio que comporte súper bien en todos los tamaños.

**Comment by JuanesPachon** [comment]
Gracias Herny! Lo tomare en cuenta.
